#include "../core/tutor.h"

static const char *const sec_cmdline[] = {
    "T:НАВИГАЦИЯ В КОМАНДНОЙ СТРОКЕ",
    "G:Движение по строке (emacs-биндинги, работают в INSERT vi-mode)",
    "R:Ctrl+a|начало строки",
    "R:Ctrl+e|конец строки",
    "R:Alt+b|слово назад",
    "R:Alt+f|слово вперёд",
    "R:Ctrl+b|символ назад",
    "R:Ctrl+f|символ вперёд",
    "B:",
    "G:Удаление",
    "R:Ctrl+w|удалить слово слева",
    "R:Alt+d|удалить слово справа",
    "R:Ctrl+u|удалить всё слева от курсора",
    "R:Ctrl+k|удалить всё справа от курсора",
    "R:Ctrl+h|удалить символ слева (= Backspace)",
    "R:Ctrl+d|удалить символ под курсором",
    "B:",
    "G:Прочее",
    "R:Ctrl+l|очистить экран (аналог clear)",
    "R:Ctrl+c|прервать текущую команду",
    "R:Ctrl+z|приостановить (SIGTSTP), fg — вернуть",
    "R:Ctrl+_|отменить последнее изменение строки",
    "R:Tab|автодополнение (через fzf-tab)",
    "R:Alt+.|вставить последний аргумент предыдущей команды",
    "N:Alt+. можно нажимать несколько раз — идёт по истории аргументов",
    "N:Активен vi-mode (bindkey -v) — см. секцию «Vi-mode в zsh»",
    "N:Ctrl+A/E/W/R явно переопределены в vi-mode INSERT для удобства",
    NULL};
static const char *const sec_history[] = {
    "T:ИСТОРИЯ КОМАНД",
    "G:Интерактивный поиск",
    "R:Ctrl+r|поиск по истории (fzf), работает в INSERT и NORMAL",
    "R:Up / Down|history-substring-search — ищет по введённому префиксу",
    "R:k / j (NORMAL)|history-substring-search в vi NORMAL mode",
    "N:Начни вводить команду, потом Up — найдёт только совпадающие",
    "B:",
    "G:Подстановки истории",
    "R:!!|повторить последнюю команду целиком",
    "R:!$|последний аргумент последней команды",
    "R:!^|первый аргумент последней команды",
    "R:!*|все аргументы последней команды",
    "R:!-2|команда два шага назад",
    "R:!git|последняя команда начинающаяся с 'git'",
    "R:!git:p|напечатать без выполнения",
    "R:^old^new|заменить old на new в последней команде",
    "B:",
    "G:Просмотр истории",
    "R:history|вывести историю с номерами",
    "R:history 20|последние 20 команд",
    "R:history | rg git|поиск по истории через ripgrep",
    "R:fc|открыть последнюю команду в $EDITOR (nvim)",
    "R:fc -l|список команд",
    "R:fc 50 60|показать команды 50–60",
    "B:",
    "G:Опции истории (активны в .zshrc)",
    "R:HIST_IGNORE_DUPS|не сохранять дубликаты подряд",
    "R:HIST_IGNORE_SPACE|не сохранять команды с пробелом в начале",
    "R:SHARE_HISTORY|история общая между всеми сессиями zsh в реальном времени",
    "N:HISTSIZE и SAVEHIST = 10000, HISTFILE = ~/.zsh_history",
    "N:Чтобы команда не попала в историю — поставь пробел перед ней",
    NULL};
static const char *const sec_aliases[] = {
    "T:АЛИАСЫ",
    "G:Файлы и навигация",
    "R:ls|lsd (замена ls)",
    "R:la|lsd -A (включая скрытые)",
    "R:ll|lsd -l (подробный список)",
    "R:lah|lsd -lAh (подробный + скрытые + human)",
    "R:tree|lsd --tree (дерево)",
    "R:.. / ... / ....|cd .. / ../.. / ../../..",
    "B:",
    "G:Поиск и инструменты",
    "R:fnvim|fzf с превью (bat) → открыть в nvim",
    "R:zi|интерактивный zoxide (zoxide query -i)",
    "B:",
    "G:Редакторы конфигов",
    "R:zshrc|nvim ~/.zshrc",
    "R:aliases|nvim ~/.config/zsh/aliases.zsh",
    "R:nvimconfig|nvim ~/.config/nvim/init.lua",
    "R:hypr|nvim ~/.config/hypr/",
    "R:bashrc|nvim ~/.bashrc",
    "B:",
    "G:Прочее",
    "R:i <pkg>|sudo pacman -S --needed",
    "R:torrent|qbittorrent",
    NULL};
static const char *const sec_functions[] = {
    "T:ФУНКЦИИ",
    "G:Файлы и система",
    "R:backup|бэкап текущей папки в ~/raf/backups/",
    "R:pwdcopy|скопировать путь текущей директории в буфер",
    "R:tn [dir]|открыть thunar в фоне (disown); без аргумента — cwd",
    "B:",
    "G:Сеть (network.zsh)",
    "R:ports|список всех LISTEN-портов (lsof)",
    "R:ports <n>|процессы на конкретном порту n",
    "R:killport <n>|завершить процесс на порту n (kill -9)",
    "R:myip|внешний IP (ifconfig.me) + локальный IP",
    "B:",
    "G:Утилиты",
    "R:weather [city]|прогноз погоды wttr.in; по умолчанию Almaty",
    "R:qr 'текст'|сгенерировать QR-код через qr-server.com API",
    "R:cow|вывести текст через cowsay | lolcat",
    "R:ff [more]|fastfetch (с поддержкой доп. конфигов)",
    "B:",
    "G:Quickshell",
    "R:qs --restart|перезапустить quickshell (pkill + nohup)",
    "R:qs <args>|обёртка для command qs",
    NULL};
static const char *const sec_plugins[] = {
    "T:ПЛАГИНЫ ZSH (zinit)",
    "G:Менеджер плагинов",
    "N:Используется zinit (вместо oh-my-zsh). Исходник: /usr/share/zinit/zinit.zsh",
    "N:Все плагины загружаются лениво (wait lucid) — не замедляют старт",
    "R:zinit update|обновить все плагины",
    "B:",
    "G:zsh-autosuggestions",
    "N:Серым цветом показывает предсказание из истории",
    "R:→ (стрелка вправо)|принять предложение целиком",
    "R:Ctrl+→|принять одно слово из предложения",
    "B:",
    "G:fzf-tab",
    "N:Заменяет стандартный Tab-completion на fzf-интерфейс",
    "R:Tab|открыть fzf-меню вместо стандартного completion",
    "N:При cd показывает превью папки через lsd",
    "B:",
    "G:zsh-history-substring-search",
    "R:Up Arrow|найти предыдущую команду с текущим префиксом",
    "R:Down Arrow|следующая команда с текущим префиксом",
    "B:",
    "G:zsh-you-should-use",
    "N:Напоминает об алиасах если вводишь полную команду",
    "B:",
    "G:OMZ плагины (через zinit snippet)",
    "R:sudo (Esc Esc)|добавить sudo к текущей или последней команде",
    "N:git — алиасы gco, gcb, gd и т.д. (OMZ git plugin)",
    NULL};
static const char *const sec_fzf[] = {
    "T:FZF",
    "G:Горячие клавиши (fzf key-bindings.zsh)",
    "R:Ctrl+r|поиск по истории команд (INSERT и NORMAL mode)",
    "R:Ctrl+t|поиск файлов в cwd, вставить в строку",
    "R:Alt+c|cd в выбранную папку",
    "N:Все три работают из любой точки командной строки",
    "B:",
    "G:Использование в командах",
    "R:cmd **<Tab>|fzf-completion для пути",
    "R:kill **<Tab>|выбрать процесс для kill",
    "R:ssh **<Tab>|выбрать хост из ~/.ssh/config",
    "R:export **<Tab>|выбрать переменную окружения",
    "N:** — триггер fzf completion, работает в большинстве команд",
    "B:",
    "G:Интерфейс fzf",
    "R:Ctrl+j / Ctrl+k|навигация вниз / вверх",
    "R:Enter|подтвердить выбор",
    "R:Ctrl+c / Esc|выйти без выбора",
    "R:Ctrl+Space|отметить элемент (multi-select)",
    "R:Tab|отметить и перейти к следующему",
    "R:Shift+Tab|снять отметку",
    "B:",
    "G:Настройки FZF_DEFAULT_OPTS (из .zshrc)",
    "R:--height=40%|окно занимает 40% терминала",
    "R:--layout=reverse|список снизу, ввод сверху",
    "R:--border=rounded|скруглённая рамка",
    "R:--info=inline|счётчик результатов в строке поиска",
    "N:Цветовая схема: Noctalia palette (мягкие пастельные тона)",
    "B:",
    "G:fzf-tab превью",
    "N:cd <Tab> показывает содержимое папки через lsd",
    "N:fnvim — fzf с bat-превью для быстрого открытия файлов в nvim",
    NULL};
static const char *const sec_tools[] = {
    "T:ИНСТРУМЕНТЫ (zoxide / starship / direnv)",
    "G:zoxide — умный cd",
    "R:z <query>|перейти в наиболее частую папку по совпадению",
    "R:zi|интерактивный выбор через fzf",
    "R:z -|вернуться в предыдущую папку",
    "N:zoxide учится: чем чаще заходишь в папку, тем выше ранг",
    "B:",
    "G:starship — prompt",
    "N:Показывает: директорию, git-ветку и статус, язык/версию проекта",
    "N:Палитра: Noctalia (настроена в starship.toml)",
    "R:starship config|открыть конфиг в $EDITOR",
    "B:",
    "G:direnv — env per directory",
    "N:При входе в папку с .envrc автоматически загружает переменные",
    "R:direnv allow|разрешить .envrc в текущей папке",
    "B:",
    "G:bat — замена cat",
    "R:cat <file>|bat с подсветкой синтаксиса (алиас)",
    "R:bat --plain <file>|без декораций (plain output)",
    "B:",
    "G:lsd — замена ls",
    "R:ls / ll / la|алиасы для lsd с разными флагами",
    "R:tree|lsd --tree (дерево)",
    "R:lsd --group-directories-first|папки в начале списка",
    "B:",
    "G:ripgrep (rg) — замена grep",
    "R:rg <pattern>|поиск по текущей директории рекурсивно",
    "N:rg автоматически игнорирует .gitignore",
    "B:",
    "G:fd — замена find",
    "R:fd <name>|быстрый поиск файлов по имени",
    NULL};
static const char *const sec_globbing[] = {
    "T:ZSH GLOBBING И ПОДСТАНОВКИ",
    "G:Стандартные wildcards",
    "R:*|любое количество любых символов",
    "R:?|один любой символ",
    "R:[abc]|один из символов a, b, c",
    "R:[a-z]|один символ из диапазона",
    "R:[^abc]|любой символ кроме a, b, c",
    "B:",
    "G:Расширенные glob (zsh)",
    "R:**|рекурсивный поиск во всех подпапках",
    "R:**/*.ts|все .ts файлы рекурсивно",
    "R:*(.)| только обычные файлы (без папок)",
    "R:*(/)| только директории",
    "R:*(x)| только исполняемые файлы",
    "R:*(@)| только симлинки",
    "R:*(om)|отсортировать по дате изменения",
    "R:*(L+1M)|файлы больше 1 МБ",
    "B:",
    "G:Отрицание и объединение",
    "R:^*.log|все файлы кроме .log  (setopt EXTENDED_GLOB)",
    "R:(*.ts|*.js)|файлы .ts или .js",
    "R:*(#i)readme*|без учёта регистра (setopt EXTENDED_GLOB)",
    "N:Для работы ^ и (#i) нужен: setopt EXTENDED_GLOB",
    "B:",
    "G:Подстановки переменных",
    "R:${var:-default}|значение или default если var не задан",
    "R:${var:=default}|присвоить default если var не задан",
    "R:${var:?error}|вывести ошибку если var не задан",
    "R:${#var}|длина строки / массива",
    "R:${var:0:5}|подстрока с 0, длина 5",
    "R:${var/old/new}|замена первого вхождения",
    "R:${var//old/new}|замена всех вхождений",
    "R:${var^^}|перевести в верхний регистр",
    "R:${var,,}|перевести в нижний регистр",
    "B:",
    "G:Подстановка команд и арифметика",
    "R:$(cmd)|подстановка вывода команды",
    "R:$((expr))|арифметика: $((2 + 2))",
    "R:<(cmd)|process substitution — как файл",
    "R:>(cmd)|process substitution — запись в команду",
    "N:Пример: diff <(sort file1) <(sort file2)",
    "B:",
    "G:Управление потоками",
    "R:cmd > file|перенаправить stdout в файл",
    "R:cmd >> file|добавить в файл",
    "R:cmd 2> file|перенаправить stderr",
    "R:cmd &> file|stdout + stderr в файл",
    "R:cmd1 | cmd2|pipe: stdout cmd1 → stdin cmd2",
    "R:cmd1 |& cmd2|pipe stdout + stderr",
    "R:cmd1 && cmd2|cmd2 только если cmd1 успешен",
    "R:cmd1 || cmd2|cmd2 только если cmd1 упал",
    "R:cmd1 ; cmd2|выполнить последовательно",
    NULL};
static const char *const sec_jobcontrol[] = {
    "T:JOB CONTROL И ПРОЦЕССЫ",
    "G:Управление задачами",
    "R:cmd &|запустить в фоне",
    "R:Ctrl+z|приостановить текущий процесс (SIGTSTP)",
    "R:jobs|список фоновых задач",
    "R:fg|вернуть последнюю задачу на передний план",
    "R:fg %2|вернуть задачу номер 2",
    "R:bg|продолжить приостановленную задачу в фоне",
    "R:bg %2|продолжить задачу 2 в фоне",
    "R:kill %1|завершить задачу 1",
    "R:disown %1|отвязать задачу от терминала",
    "N:disown используется в функциях nhn(), qs(), obsid — они не падают при "
    "закрытии терминала",
    "B:",
    "G:Процессы",
    "R:ps aux | rg name|найти процесс по имени",
    "R:pgrep name|PID процессов по имени",
    "R:pkill name|завершить процессы по имени",
    "R:kill -9 <pid>|принудительно завершить",
    "R:ports|список LISTEN-портов (функция из network.zsh)",
    "R:killport <n>|завершить процесс на порту n",
    "B:",
    "G:nohup и disown",
    "N:nohup cmd &  — команда продолжает работать после закрытия терминала",
    "N:cmd & disown — то же, но без создания nohup.out",
    "N:Паттерн из конфига: nohup qs ... >/dev/null 2>&1 & disown",
    "B:",
    "G:Полезные комбинации",
    "R:jobs -l|список задач с PID",
    "R:wait|ждать завершения всех фоновых задач",
    "R:wait %1|ждать конкретную задачу",
    "N:Ctrl+c отправляет SIGINT — корректное завершение",
    "N:Ctrl+z отправляет SIGTSTP — пауза, можно продолжить через fg/bg",
    NULL};
static const char *const sec_vimode[] = {
    "T:VI-MODE В ZSH",
    "G:Режимы и индикаторы",
    "N:Активируется через bindkey -v. KEYTIMEOUT=1 — быстрый выход по ESC",
    "N:RPROMPT показывает текущий режим:",
    "R:I (синий)|INSERT mode — ввод текста, emacs-биндинги активны",
    "R:N (красный)|NORMAL mode — навигация и редактирование vi",
    "N:Курсор: beam (|) в INSERT, block (█) в NORMAL — меняется автоматически",
    "N:При выходе из zsh курсор сбрасывается в beam",
    "B:",
    "G:Переключение режимов",
    "R:Esc|INSERT → NORMAL",
    "R:i|NORMAL → INSERT (перед курсором)",
    "R:a|NORMAL → INSERT (после курсора)",
    "R:I|NORMAL → INSERT (начало строки)",
    "R:A|NORMAL → INSERT (конец строки)",
    "R:v|NORMAL → VISUAL (выделение)",
    "B:",
    "G:Навигация в NORMAL mode",
    "R:h / l|символ влево / вправо",
    "R:w / b|слово вперёд / назад",
    "R:e|конец следующего слова",
    "R:0 / ^|начало строки / первый непробельный символ",
    "R:$|конец строки",
    "R:f<c> / F<c>|перейти к символу c вперёд / назад",
    "R:t<c> / T<c>|перейти до символа c вперёд / назад",
    "R:; / ,|повторить f/t вперёд / назад",
    "B:",
    "G:Редактирование в NORMAL mode",
    "R:x|удалить символ под курсором",
    "R:d<motion>|удалить по motion: dw, db, d$, d0",
    "R:dd|удалить строку (всю командную строку)",
    "R:c<motion>|удалить по motion + войти в INSERT",
    "R:cc / S|очистить строку и войти в INSERT",
    "R:r<c>|заменить символ на c без выхода в INSERT",
    "R:R|режим замены (перезапись символов)",
    "R:y<motion>|скопировать: yw, y$",
    "R:yy|скопировать всю строку",
    "R:p / P|вставить после / до курсора",
    "R:u|отмена (undo) — в пределах текущей строки",
    "B:",
    "G:Биндинги INSERT mode (явно переопределены)",
    "R:Ctrl+a|начало строки",
    "R:Ctrl+e|конец строки",
    "R:Ctrl+w|удалить слово слева",
    "R:Ctrl+r|поиск по истории (fzf)",
    "R:Backspace / Ctrl+h|удалить символ слева (корректно после ESC)",
    "N:Backspace явно переопределён — без этого в vi-mode он ломается",
    "B:",
    "G:История в NORMAL mode",
    "R:k|предыдущая команда с совпадающим префиксом (substring-search)",
    "R:j|следующая команда с совпадающим префиксом",
    "R:Ctrl+r|поиск по истории (fzf) — работает в обоих режимах",
    "N:k/j переопределены на history-substring-search (не vi-up-line)",
    "N:Биндинги применяются лениво при первом precmd после загрузки плагина",
    "B:",
    "G:Текстовые объекты (VISUAL и operator-pending)",
    "N:Работают в VISUAL mode и после операторов d/c/y в NORMAL:",
    "R:ci\" / ca\"|изменить внутри / включая двойные кавычки",
    "R:ci' / ca'|изменить внутри / включая одинарные кавычки",
    "R:ci` / ca`|изменить внутри / включая обратные кавычки",
    "R:ci( / ca(|изменить внутри / включая скобки ()",
    "R:ci[ / ca[|изменить внутри / включая скобки []",
    "R:ci{ / ca{|изменить внутри / включая скобки {}",
    "R:ci< / ca<|изменить внутри / включая угловые скобки",
    "N:Аналогично di\", yi( и т.д. — удалить / скопировать",
    "N:Реализовано через autoload select-bracketed select-quoted",
    "B:",
    "G:Surround (ys / cs / ds)",
    "N:Реализовано через autoload surround — аналог vim-surround",
    "R:ys<motion><c>|обернуть motion в символ c",
    "R:ysiw\"|обернуть слово под курсором в двойные кавычки",
    "R:ysiw(|обернуть слово в скобки (со пробелами)",
    "R:ysiw)|обернуть слово в скобки (без пробелов)",
    "R:cs\"'|заменить окружающие \" на '",
    "R:cs'\"|заменить окружающие ' на \"",
    "R:ds\"|удалить окружающие двойные кавычки",
    "R:ds(|удалить окружающие скобки",
    "R:S<c> (VISUAL)|обернуть выделение в символ c",
    "N:Привязки: cs / ds / ys в vicmd, S в visual",
    "B:",
    "G:Советы",
    "N:ESC Esc (двойной) — добавляет sudo (OMZ sudo plugin, работает в обоих "
    "режимах)",
    "N:В NORMAL mode набери число перед motion: 3w — три слова вперёд",
    "N:Команда : в NORMAL в zsh не открывает ex — это просто символ",
    "N:Для сложного редактирования строки — fc: откроет nvim с командой",
    NULL};

static const TutorSection sections[] = {
    {"Навигация в командной строке", sec_cmdline},
    {"История команд", sec_history},
    {"Алиасы", sec_aliases},
    {"Функции  (backup / ccmd / network / qs / weather...)", sec_functions},
    {"Плагины zinit  (autosuggestions / fzf-tab / sudo / dirhistory...)", sec_plugins},
    {"fzf  (Ctrl+r / Ctrl+t / Alt+c / completion)", sec_fzf},
    {"Инструменты  (zoxide / bat / eza / rg / fd / direnv / uv / starship)", sec_tools},
    {"Globbing и подстановки", sec_globbing},
    {"Job control и процессы", sec_jobcontrol},
    {"Vi-mode в zsh  (режимы / text objects / surround / курсор / RPROMPT)", sec_vimode},
};

const TutorConfig tutor_config = {
    .title = "ZSHTUTOR",
    .tagline = "zsh · zinit · vi-mode · fzf · zoxide · starship · eza · bat · rg · fd",
    .title_color = "\033[38;5;111m",
    .key_width = 22,
    .sections = sections,
    .section_count = sizeof(sections) / sizeof(sections[0]),
};
